[project]
name = "public-info"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cryptography>=45.0.5",
    "functions-framework>=3.8.3",
    "google-cloud-firestore>=2.21.0",
    "google-cloud-functions>=1.20.4",
]
