swagger: "2.0"
info:
  title: simulo-status-api
  version: 1.0.0

schemes:
  - https

paths:
  /public-info:
    get:
      summary: Get public status information
      operationId: getPublicInfo
      x-google-backend:
        address: https://REGION-PROJECTID.cloudfunctions.net/public-info
      responses:
        "200":
          description: A successful response containing public status information.
          schema:
            type: string
  /log:
    post:
      summary: Get log backend infrastructure state
      operationId: getLogInfo
      x-google-backend:
        address: https://REGION-PROJECTID.cloudfunctions.net/log
      responses:
        "200":
          description: The information was logged
          schema:
            type: string
  /private-info:
    options:
      summary: Support CORS preflight requests
      operationId: optionsPrivateInfo
      x-google-backend:
        address: https://REGION-PROJECTID.cloudfunctions.net/private-info
      responses:
        "200":
          description: Always returned
          schema:
            type: string
    post:
      summary: Get private status information
      operationId: getPrivateInfo
      x-google-backend:
        address: https://REGION-PROJECTID.cloudfunctions.net/private-info
      responses:
        "200":
          description: The information was logged
          schema:
            type: string
